### ISSUE TITLE
Java 17 support and official distributions

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#569]
Currently Jenkinsfile Runner ships only with Java 11. @timja @basil and other contributors made a lot of work to ship Java 17 preview support in the Jenkins core, and it would be awesome to ship Jenkinsfile Runner distributions for it too

## Scope

- [ ] Add test automation fo Java 17 compatibility
- [ ] Create preview Docker distributions for Java 17
- [ ] Document Java 17 support policy

**Comment by ssthom** [comment]
I started on a PR https://github.com/jenkinsci/jenkinsfile-runner/pull/723 to upgrade to Java 17 and newer Jenkins release 2.462.3. Having trouble getting the builds to work in the PR. But locally I was able to compile and build the docker image with Maven 3.9.9 and Java 17. Also Java 8/11 are out of support so I think we can switch directly to 17 https://www.jenkins.io/doc/book/platform-information/support-policy-java/

```
mvn clean install -Denvironment=test -Ppackage-app,package-vanilla,jacoco,run-its -DargLine="--add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED"
```

```
podman build -t jenkins4eval/jenkinsfile-runner -f packaging/docker/unix/eclipse-temurin-17-jre/Dockerfile . --arch x86_64
```

**Comment by oleg-nenashev** [comment]
Yes, Java 17 or even 21 are fine
