### ISSUE TITLE
Make Jenkinsfile Runner a Jenkins sub-project

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#571]
Jenkinsfile Runner got some adoption, and it would be awesome to promote it to the official sub-project status. It would help to attract more contributors to the project.

It would include the following repositories:

* Jenkinsfile Runner itself
* Image packs: https://github.com/jenkinsci/jenkinsfile-runner-image-packs
* Distribution for GitHub Actions: https://github.com/jenkinsci/jenkinsfile-runner-github-actions
* Distributions for other systems. Maybe @carlossg would be interested to move over AWS Lambda and Oracle Fn packages over to the Jenkins Community
* TBD: https://github.com/jenkinsci/jenkinsfile-runner-test-framework
* TBD: Reference implementation for ci.jenkins.io: https://github.com/jenkinsci/ci.jenkins.io-runner

## Scope

- [ ] Approve creating new sub-project at the Jenkins governance meeting
- [ ] Consolidate permissions and repositories
- [ ] Document the project on jenkins.io
- [ ] Public announcement
