### ISSUE TITLE
Tekton Template for Jenkinsfile Runner

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#572]
It would be awesome to have a standard template for Tekton that allows easily running Jenkinsfile runner as a Tekton step. 

### Scope

- [ ] New repository for Tekton templates
- [ ] TBD: Better adaptation of Jenkinsfile Runner for Kubernetes deployments
- [ ] Tekton templates for vanilla Jenkinsfile runner and Image Packs that do not require configuration and image repackaging
- [ ] Tekton template for building Jenkinsfile Runner custom images, with help of Custom WAR Packager and YAML definitions. Depends on #570 

### Stakeholders

* Tekton community - TBD (@afrittoli)
* Jenkins X - TBD
* SAP as StewardCI developers/maintainers
