### ISSUE TITLE
JFR GitHub Action refresh

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#576]
There are PoC GitHub Actions for Jenkinsfile Runner that were created by @jonico a few years ago: https://github.com/jenkinsci/jenkinsfile-runner-github-actions . It is a nice application for Jenkinsfile Runner, and it would be great to update them to the recent JFR versions and packaging flows.

### Scope

- [ ] GitHub Action(s) for vanilla Jenkinsfile runner and Image Packs that do not require configuration and image repackaging
- [ ] GitHub Action for building Jenkinsfile Runner custom images, with help of Custom WAR Packager and YAML definitions. Depends on #570 
- [ ] Example repositories that use GitHub Actions
