### ISSUE TITLE
Deprecate Java 1.8 support

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#584]
Currently Jenkinsfile Runner base images are distributed with Java 8 by default. Also, there is ongoing work on Java 17 support in Jenkins and Jenkinsfile Runner in #569. Once it is shipped, it might make sense to drop Java 8 support. It is also reasonable to switch to Java 11, because Quarkus 2 does no longer support Java 8 and we want to adopt it in #214 

## Scope

- [ ] Document the new Java support policy
- [ ] Update the Maven image pack so that there is still a JDK 1.8 edition. It will require bundling two versions in the image
- [ ] Remove JDK 1.8 specific code

## References

- [Java support policy in Jenkins](https://www.jenkins.io/doc/administration/requirements/java/)
- #596
