### ISSUE TITLE
Build-time Jenkinsfile Runner initialization with Quarkus

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#585]
Currently Jenkinsfile Runner takes a few seconds to initialize due to loading of plugins and configurations. In many cases it can be done during the build time so that Jenkinsfile Runner starts up much faster. [Quarkus](https://quarkus.io/) provides support for build-time initialization even if native images are not used

## Why?

A few seconds of startup are not a problem for common pipelines that take minutes and hours. At the same time it becomes a serious issue if Jenkinsfile Runner is used to execute particular Jenkins steps in a container, e.g. within Tekton. Having an immediate startup there would significantly improve developer experience and optimiz resource usage

## Scope

- [ ] New Quarkus extension for Jenkinsfile Runner that can do packaging based on the Maven specification. This extension should initialize Jenkins and plugins during the build time. Configurations would be nice too but have to be optional
- [ ] Developer guidelines for the new mode
- [ ] Demo for the new mode
- [ ] List the extension on the Quarkus marketplace

## References

* [Writing Quarkus extensions](https://quarkus.io/guides/writing-extensions)
