### ISSUE TITLE
Observability with OpenTelemetry

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#586]
There are OpenTelemetry plugins for Jenkins but they do not provide traceability for Jenkinsfile Runner specific events, e.g. Jenkinsfile Runner or internal Jenkins initialization. It would be great to support OpenTelemetry by default.

## Scope

- [ ] Bundle OpenTelemetry Client into Jenkinsfile runner
- [ ] Add options to enable OpenTelemetry. If enabled, allow submitting OpenTelemetry traces, metrics and logs. Full scope is TBD, the task is likely to be split
- [ ] TBD: Include Open Telemetry plugins into the default distribution. To be discussed with @cyrille-leclerc and @Aki-7, probably requires performance optimizations for the cases when the plugins are disabled
