### ISSUE TITLE
Java 17 Distributions

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/jenkinsfile-runner#596]
### What feature do you want to see added?

Currently the Jenkinsfile Runner support Java 17 while the Jenkins core provides it as Preview. It would be great to support Java 17 and to provide the Docker images for this platform

### Scope

- [ ] Create a  working PoC
- [ ] Address the reported issues, e.g. #589
- [ ] Java 17 Docker images
- [ ] Java 17 test automation in the CI/CD pipeline
- [ ] Announce Java 17 preview

### References

* https://www.jenkins.io/doc/administration/requirements/java/

**Comment by oleg-nenashev** [comment]
Duplicates #569
